### ISSUE TITLE
Wrong colors on Windows 11 with dark mode enabled

### ISSUE THREAD

**Issue by DryTaste** [ricewind012/win95-themes#5]
As the title states; the theme exhibits the wrong (or rather unadvertised) colours when windows dark mode is turned on. 

Sadly Windows doesn't have an exclude programs feature from it's dark mode, not sure if this is a feature request i should raise for this theme or for millennium.

**Comment by ricewind012** [comment]
is it light when dark mode is enabled ? steam seems to ignore it on linux (and probably on windows too), that's why

**Comment by ricewind012** [comment]
It's intended if system dark mode is enabled, but steam is a special case. I do have plans on making it optional in some way, but for now you can disable auto-updates and remove the following: https://github.com/ricewind012/win95-themes/blob/master/dist/steam/steam.css#L92-L113 it should be located in `c:\program files (x86)\steam\steamui\skins\win95-themes-master\dist\steam`

**Comment by DryTaste** [comment]
> It's intended if system dark mode is enabled, but steam is a special case. I do have plans on making it optional in some way, but for now you can disable auto-updates and remove the following: https://github.com/ricewind012/win95-themes/blob/master/dist/steam/steam.css#L92-L113 it should be located in `c:\program files (x86)\steam\steamui\skins\win95-themes-master\dist\steam`

Thank you for the fast reply and solution! Adding an option for it in millennium would be nice yeah. 
(but tbh windows should just have an exclude applications from dark mode option if you ask me)

**Comment by ricewind012** [comment]
it will be optional only because the behavior doesn't really align with vs code (and soon discord) either
